### ISSUE TITLE
app will crash 

### ISSUE THREAD

**Issue by IBit-Company** [fornewid/neumorphism#51]
Version used:
com.github.fornewid:neumorphism:0.2.1
android api 23

XML:
`<soup.neumorphism.NeumorphCardView
        android:id="@+id/neumorphCardView"
        style="@style/smallRoundedButton"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="8dp"
        android:layout_marginEnd="8dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/constraintLayout"/>`

Style:
`<style name="smallRoundedButton" parent="android:Widget">
        <item name="android:padding">6dp</item>
        <item name="android:stateListAnimator">@animator/button_state_list_anim_neumorph</item>
        <item name="android:focusable">true</item>
        <item name="android:clickable">true</item>
        <item name="android:scaleType">center</item>
        <item name="neumorph_shadowElevation">4dp</item>
        <item name="neumorph_shadowColorLight">@color/lightShadow</item>
        <item name="neumorph_shadowColorDark">@color/darkShadow</item>
        <item name="neumorph_shapeType">flat</item>
        <item name="neumorph_shapeAppearance">@style/CustomShapeAppearance16</item>
    </style>`

Logcat Error:
` java.lang.OutOfMemoryError: Failed to allocate a 4759564 byte allocation with 634240 free bytes and 619KB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
        at soup.neumorphism.internal.blur.BlurProvider.blur(BlurProvider.kt:51)
        at soup.neumorphism.internal.blur.BlurProvider.blur(BlurProvider.kt:42)
        at soup.neumorphism.internal.blur.BlurProvider.blur$default(BlurProvider.kt:34)
        at soup.neumorphism.internal.shape.FlatShape$toBlurredBitmap$1.invoke(FlatShape.kt:92)
        at soup.neumorphism.internal.shape.FlatShape.toBlurredBitmap(FlatShape.kt:104)
        at soup.neumorphism.internal.shape.FlatShape.updateShadowBitmap(FlatShape.kt:84)
        at soup.neumorphism.NeumorphShapeDrawable.draw(NeumorphShapeDrawable.kt:283)
        at android.view.View.drawBackground(View.java:16370)
        at android.view.View.draw(View.java:16169)
        at android.view.View.draw(View.java:16090)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882)
        at android.view.View.draw(View.java:16181)
        at android.view.View.draw(View.java:16090)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16088)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16088)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16088)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16088)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16088)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16181)
        at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
        at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2728)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:606)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

its works fine in some newer android phone but when running on phone with android api 23 it will crash!!
how can i solve that?

i try to use normal card view and its works fine.

**Comment by mdumarkhan1** [comment]
> Version used:
> com.github.fornewid:neumorphism:0.2.1
> android api 23
> 
> XML:
> `<soup.neumorphism.NeumorphCardView android:id="@+id/neumorphCardView" style="@style/smallRoundedButton" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginStart="8dp" android:layout_marginEnd="8dp" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/constraintLayout"/>`
> 
> Style:
> `<style name="smallRoundedButton" parent="android:Widget"> <item name="android:padding">6dp</item> <item name="android:stateListAnimator">@animator/button_state_list_anim_neumorph</item> <item name="android:focusable">true</item> <item name="android:clickable">true</item> <item name="android:scaleType">center</item> <item name="neumorph_shadowElevation">4dp</item> <item name="neumorph_shadowColorLight">@color/lightShadow</item> <item name="neumorph_shadowColorDark">@color/darkShadow</item> <item name="neumorph_shapeType">flat</item> <item name="neumorph_shapeAppearance">@style/CustomShapeAppearance16</item> </style>`
> 
> Logcat Error:
> ` java.lang.OutOfMemoryError: Failed to allocate a 4759564 byte allocation with 634240 free bytes and 619KB until OOM at dalvik.system.VMRuntime.newNonMovableArray(Native Method) at android.graphics.Bitmap.nativeCreate(Native Method) at android.graphics.Bitmap.createBitmap(Bitmap.java:831) at android.graphics.Bitmap.createBitmap(Bitmap.java:808) at android.graphics.Bitmap.createBitmap(Bitmap.java:775) at soup.neumorphism.internal.blur.BlurProvider.blur(BlurProvider.kt:51) at soup.neumorphism.internal.blur.BlurProvider.blur(BlurProvider.kt:42) at soup.neumorphism.internal.blur.BlurProvider.blur$default(BlurProvider.kt:34) at soup.neumorphism.internal.shape.FlatShape$toBlurredBitmap$1.invoke(FlatShape.kt:92) at soup.neumorphism.internal.shape.FlatShape.toBlurredBitmap(FlatShape.kt:104) at soup.neumorphism.internal.shape.FlatShape.updateShadowBitmap(FlatShape.kt:84) at soup.neumorphism.NeumorphShapeDrawable.draw(NeumorphShapeDrawable.kt:283) at android.view.View.drawBackground(View.java:16370) at android.view.View.draw(View.java:16169) at android.view.View.draw(View.java:16090) at android.view.ViewGroup.drawChild(ViewGroup.java:3609) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882) at android.view.View.draw(View.java:16181) at android.view.View.draw(View.java:16090) at android.view.ViewGroup.drawChild(ViewGroup.java:3609) at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) at android.view.View.draw(View.java:16088) at android.view.ViewGroup.drawChild(ViewGroup.java:3609) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) at android.view.View.draw(View.java:16088) at android.view.ViewGroup.drawChild(ViewGroup.java:3609) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) at android.view.View.draw(View.java:16088) at android.view.ViewGroup.drawChild(ViewGroup.java:3609) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) at android.view.View.draw(View.java:16088) at android.view.ViewGroup.drawChild(ViewGroup.java:3609) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) at android.view.View.draw(View.java:16088) at android.view.ViewGroup.drawChild(ViewGroup.java:3609) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) at android.view.View.draw(View.java:16181) at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690) at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2728) at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642) at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858) at android.view.Choreographer.doCallbacks(Choreographer.java:670) at android.view.Choreographer.doFrame(Choreographer.java:606) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5417) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`
> 
> its works fine in some newer android phone but when running on phone with android api 23 it will crash!!
> how can i solve that?
> 
> i try to use normal card view and its works fine.

Faced the same issue with one of my live apps. Please fix it or provide any solution.
